version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:e01a5ea0de11b220b600bf1998bebabd13713f7b
  
workflows:
  precompile:
    jobs:
      - elixir/precompile_for_macos_arm: &parameters
          package-name: srt
          expected-version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - elixir/precompile_for_linux:
          <<: *parameters
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_arm
            - elixir/precompile_for_linux
          version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
