version: 2.1
orbs:
  elixir: membraneframework/elixir@1.5

workflows:
  precompile:
    jobs:
      - elixir/precompile_for_macos_arm: &parameters
          package-name: srt
          expected-version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - elixir/precompile_for_linux_x86:
          <<: *parameters
      - elixir/precompile_for_linux_arm:
          <<: *parameters
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_arm
            - elixir/precompile_for_linux_x86
            - elixir/precompile_for_linux_arm
          version: << pipeline.git.tag >>
          context: publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
